processes:
  gui:
    title: "Rembrain Robot Framework Example (Local)"
    keep_alive: false
    consume:
      - image_orig
      - image_processed

  image_capture:
    publish:
      - image_orig

  processor:
    device: "cpu"
    publish:
      - image_processed
    consume:
      - image_orig

shared_objects:
  exit_flag: "Value:bool"

description:
  subsystem: local_example
  robot: local_example_robot
